### ISSUE TITLE
add contributing guidelines, issue guidelines and PR guidelines

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/meet-maynard#1]
## Problem

New comers to the project don't know how to get started and nor how to go from idea to -> PR -> get it merged.

## Solution
* add contributing guidelines
* add issues guidelines
* add PR guidelines

**Comment by isometimescode** [comment]
We also need to create a group for reviewers to be tagged, permissions for merging etc?

**Comment by isometimescode** [comment]
Also a LICENSE?

**Comment by isometimescode** [comment]
@zassmin do we have a code of conduct markdown file we use for repos? I know we have one for events, and there is something like http://contributor-covenant.org/ in case we don't.
