### ISSUE TITLE
add papertrail

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/meet-maynard#30]
## Problem

meet-maynard doesn't have paper trail

## Solution
- add paper trail
- ensure key information isn't stored

**Comment by isometimescode** [comment]
Papertrail has been added to `wwcode-maynard`. @zassmin LMK if you want it for `wwcode-maynard-staging` as well?

We have been filtering out secret key data for Bugsnag and the logs locally, so we should be good there, but I can't tell until one of the scheduler tasks have run. But this is what the logs look like right now:
https://papertrailapp.com/systems/1002111001/events
