### ISSUE TITLE
we aren't monitoring heroku scheduler tasks

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/meet-maynard#41]
## Problem

we aren't monitoring heroku scheduler tasks and therefore didn't quickly notice one of our tasks was running for 19 hours (at least) 🙈 : 

```
$ heroku ps -a wwcode-maynard
=== scheduler (Hobby): bundle exec rake data_import:rsvps (1)
scheduler.5538: up 2017/08/06 17:30:37 -0700 (~ 19h ago)
```

## Solution
- add monitoring for the heroku scheduler - https://devcenter.heroku.com/articles/deadmanssnitch

**Comment by littleforest** [comment]
Are we okay with $5/mo for 3 snitches?  The free plan only has 1. Or we could do $19/mo for 100.  At the moment we only have 3 rake tasks on Meet Maynard so we could start with that.

**Comment by zassmin** [comment]
@littleforest is it one snitch per rake task? what's a snitch?

**Comment by littleforest** [comment]
oh well, I was thinking to use a separate one, but that's a good point, maybe I can use the same one.  The snitch is the URL that gets posted to.  I haven't been able to get any data posted yet, but let me keep playing around.

**Comment by littleforest** [comment]
Okay, it does seem that we need a separate snitch for each task.  The way it works is we trigger the snitch a first time, and once it's activated, it will wait for another message every hour or day, or whatever we set the interval at.  If it doesn't hear from the rake task, then it will alert us.  So we definitely need separate snitches for each task.

**Comment by isometimescode** [comment]
Just FYI but it looks like Papertrail has something similar to find logs that *didn't* happen. If we are thinking of paying for the other service, maybe this is something to consider since we already pay for Papertrail?

http://help.papertrailapp.com/kb/how-it-works/alerts/#inactivity-alerts

**Comment by zassmin** [comment]
@littleforest am I blocking you with anything here?

**Comment by littleforest** [comment]
PR just needs a review.
