### ISSUE TITLE
pull from meetup group endpoint

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/meet-maynard#7]
## Problem

We don't store all the group info from meetup

## Solution
* pull all the group data for the given meet pro urlname, `womenwhocode`, https://www.meetup.com/meetup_api/docs/pro/:urlname/groups/ 
* store all the data returned

**Comment by littleforest** [comment]
@zassmin, @isometimescode this is what the group data output looks like.  I'm thinking to create `json` fields for `topics`, `category`, and `organizers`, or do we want to create members, categories, topics tables and pull out all of the data into relational tables instead?

```
{"id"=>21591264,
  "name"=>"Women Who Code Pune",
  "description"=>
   "<p><b>Big log description</b></p>\n",
  "lat"=>18.530000686645508,
  "lon"=>73.83999633789062,
  "city"=>"Pune",
  "country"=>"India",
  "urlname"=>"Women-Who-Code-Pune",
  "member_count"=>508,
  "average_age"=>27.235300064086914,
  "founded_date"=>1481835203000,
  "pro_join_date"=>1481835560000,
  "last_event"=>1496464200000,
  "past_events"=>5,
  "upcoming_events"=>0,
  "past_rsvps"=>235,
  "rsvps_per_event"=>47.0,
  "repeat_rsvpers"=>53,
  "topics"=>
   [{"id"=>563, "name"=>"Open Source", "urlkey"=>"opensource", "lang"=>"en_US"},
    {"id"=>10296, "name"=>"Women in Technology", "urlkey"=>"witi", "lang"=>"en_US"},
    {"id"=>45181, "name"=>"Women Programmers", "urlkey"=>"women-programmers", "lang"=>"en_US"},
    {"id"=>48471, "name"=>"Computer programming", "urlkey"=>"computer-programming", "lang"=>"en_US"},
    {"id"=>87614, "name"=>"DevOps", "urlkey"=>"devops", "lang"=>"en_US"},
    {"id"=>725122, "name"=>"learn to code", "urlkey"=>"learn-to-code", "lang"=>"en_US"},
    {"id"=>1398192, "name"=>"Women Who Code", "urlkey"=>"women-who-code", "lang"=>"en_US"},
    {"id"=>1489532, "name"=>"WWC", "urlkey"=>"wwc", "lang"=>"en_US"},
    {"id"=>1505373, "name"=>"Coding for Beginners", "urlkey"=>"coding-for-beginners", "lang"=>"en_US"}],
  "category"=>[{"id"=>34, "name"=>"Tech", "shortname"=>"Tech", "sort_name"=>"Tech"}],
  "gender_unknown"=>0.005200000014156103,
  "gender_female"=>0.5598999857902527,
  "gender_male"=>0.42969998717308044,
  "gender_other"=>0.005200000014156103,
  "organizers"=>
   [{"member_id"=>112589802, "permission"=>"coorganizer", "name"=>"Janki"},
    {"member_id"=>222010349, "permission"=>"coorganizer", "name"=>"Sonal Bobde"},
    {"member_id"=>129339582, "permission"=>"organizer", "name"=>"Women Who Code"}],
  "status"=>"Active"}
```

**Comment by isometimescode** [comment]
@zassmin @littleforest I was thinking they'd each be their own objects/table, but I'm actually not sure how the data is read or used by Chartio. 
And looking at the old [Go App](https://github.com/WomenWhoCode/meetupgoers/blob/master/crawler/group_crawler.go#L14), it might have been skipping those 3 fields altogether?

**Comment by littleforest** [comment]
Okay I will store them as json type for now, and we can pull them out separately later if needed.

**Comment by littleforest** [comment]
The [Pro Group response](https://www.meetup.com/meetup_api/docs/pro/:urlname/groups/) is different from the [Group response](https://www.meetup.com/meetup_api/docs/:urlname/#get).  Do we want to merge these data into a single object, or keep a separate Pro Group object?

**Comment by zassmin** [comment]
@littleforest @isometimescode good point about the pro vs group. I didn't realize which pro returned nested json data. 

I would omit the topics, category and organizer's for now. When we get to that point where can store in separate models. That current data doesn't block our ability to get rsvps question/answer info anyway. Plus, Chartio isn't friendly about json data. Similarly, I don't think we need 2 different models for pro vs group just yet.

**Comment by littleforest** [comment]
Okay -- how about I name the model `GroupStat` then, and we can use `Group` for the group endpoint later if needed?

**Comment by zassmin** [comment]
@littleforest good call!
