### ISSUE TITLE
deploy app to heroku or any other hosting service

### ISSUE THREAD

**Issue by zassmin** [WomenWhoCode/meet-maynard#9]
# Problem

We need to deploy this app to be able to schedule regular API requests. 

# Solution
* deploy to heroku or something simpler
* set up postgres add-on
* add meetup api key
* ensure this project knows to access meetup api via env

# Other points
* Does Heroku create `config/database.yml` automatically for non-Rails app? If not, need to commit that file and use ENV vars to be able to customize in the dev environment.
* Does Heroku set `RACK_ENV` by default for non-Rails app?  If so, then change name of environment variable in `config/environment.rb`.

**Comment by isometimescode** [comment]
We could probably find another PaaS to run on AWS or Digital Ocean for comparable cost, but I think we'd have to figure out a bunch of deployment stuff to integrate GitHub and review apps and the like, that perhaps is unnecessary work for a simple app like this. Unless we were looking to use this chance as an experiment & training opportunity for moving our other apps to a new service, then I'd vote to keep Heroku for a lower learning curve for the rest of the core team.

**Comment by littleforest** [comment]
@zassmin should I just port over the existing meetup API code from the website? or do you want me to just set up some trivial call for now as part of this task.
